In [ ]:
# Yuval Brief 205639107

# variable types :
 
k = 10  # starts an integer
k1 = k/3  # changes it to a float on its own
print(type(k), type(k1))

l = 10 
print(k==l, k is l)  # k and l are the same number and stored at the same place
print(id(k)-id(l))

print('--------')

a = 1500
b = 1500 
print(a==b, a is b)  # if the numbers are large enough they are stored at different locations
print(id(a)-id(b))

print('--------')

# lists :

list2 = [1, 2, 3]
list3= [1, 2, 3]
print(list2==list3, list2 is list3)  # the same but stored elsewhere
print(id(list2)-id(list3))
list3[0] = 0
print(list2, list3)  # changes on the new doesn't effect old

list4 = list2[:]  # another way of copying a list. stored elsewhere too
print(id(list4) - id(list2))

list5 = [2,1,3]
print(list5 == list2)  # order matters

# tuples : like lists only can't be changed

tuple1 = (1, 2, 3)
#tuple1[1] = 3  # will error


In [ ]:
# adding an element to a tuple :

tuple2 = (1, 2, 3, 4)
tuple3 = tuple2[:2] + (10,) + tuple2[2:]  # add the 10 in the middle
print(tuple3)
tuple4 = (0,) +tuple2[:] + (5,) # adds 0 in the start and 5 in the end
print(tuple4)

print('---------') 

#converting a list to a tuple :

list1 = [1, 2, 5]
tuple1= tuple(list1)
print(tuple1, type(tuple1))

print('---------')

# list slicing and indexing examples :

list2 = [1, -2, 5, 10, -10, 500, 99, -3]
print(list2[::2]) # every even indexed element
print(list2[::-1]) # reverses the list
print(list2[5:2:-1]) #reverses and starts and stops a a specific place

print('---------')

# list comps example :

list3 = [(x,y) for x in range(7) for y in range(7) if x*y % 2 == 1] 
print(list3) # a list of all the tuples only containing odds from 0 to 6

print('----------')

# more actions on lists :

list4 = [10, 25, 21, -19, 40]
print(sorted(list4)) # sorts the list
print(max(list4)) # its largest element
print(list4.count(25)) # how many times 0 is in the list
list5= ['ten', 'twenty five', 'twenty one', 'negetive nineteen', 'fourty']
zipped = zip(list4,list5)
print(list(zipped))  # a list of the corresponding tuples from the lists 4,5


In [ ]:
 # loops example: a basic english learning game

sentence = 'i like to __1__ ice cream in the summer' # a sentence with a blank word
ans = 'eat'
ans_count = 1
ans1 = ''
print(sentence)
while ans_count <= 4 and ans1 != ans :  # you have to input your answer, you have 3 attempts
  if ans_count <= 3:
   ans1 = input('enter your answer: ')
   if ans1 == ans :
    print('correct!')
   else:
    print('try again :)')
    ans_count += 1
  else:
    print('better luck next time!')
    ans_count += 1


In [ ]:
 # recursive function example :

 def fib(n) :    # the n fibonacci number
   if n == 0 or n == 1 :
     return 1
   else :
        return fib(n-1) + fib(n-2)

def fibsum(n) :
   if n == 0 :
     return 1
   else :
     return fib(n) + fibsum(n-1)

 print(fib(5),fibsum(4))    

In [ ]:
 # numpy :

import numpy as np

v = np.array([1, 2.5, 3]) # in the nd array all of the elements are the same type
for i in v:
  print(type(i))
v[1] = 2 # put an integer in a float array, remains a float array
print(v,type(v[0]))

print('---------')

w = np.array([1,3,5])
w[0] = 1.1  # can't put a float in an integer array
print(w,type(w[0]))  # remains the same

print('--------')

# combining nd arrays together :

v1 = np.array([[10, 20, 30]])
v2 = np.array([[5, 1.9, 2]])
v3 = np.array([[1, 2, 3],[4, 5, 6],[7, 8 ,9]])

print(np.concatenate((v1, v2), axis=None))  # combines both in one row
print(np.concatenate((v1, v2), axis= 0))   # puts them in rows in 2X3 matrix
print(np.concatenate((v1, -1, -2, v2), axis=None))  # can allso add numbers to arrays
print(np.concatenate((v3,v2),axis=0))  # add a new row to a matrix
print(np.concatenate((v3, v1.T), axis=1)) # add a new column to a matrix

print('--------')

# shaping :
print(v1.shape, v3.shape)  # an nd array has a shape.
v33 = v3.reshape(9) # reshapes the 3x3 matrix to a 9X1 row
print(v33)
print(v3) 
print(id(v33)-id(v3)) # stores in new place in memory
v33[0] = 10
print(v33, v3)  # changes to new affect old

print('-------')

u1 = np.arange(4) # like range
u2 = u1.reshape(2,2).copy() # the copy will fix this problem
print(u1)
print(u2)
u2[0,0] = 10
print(u1)
print(u2)



<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
[1. 2. 3.] <class 'numpy.float64'>
---------
[1 3 5] <class 'numpy.int64'>
--------
[10.  20.  30.   5.   1.9  2. ]
[[10.  20.  30. ]
 [ 5.   1.9  2. ]]
[10.  20.  30.  -1.  -2.   5.   1.9  2. ]
[[1.  2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]
 [5.  1.9 2. ]]
[[ 1  2  3 10]
 [ 4  5  6 20]
 [ 7  8  9 30]]
--------
(1, 3) (3, 3)
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
-366304
[10  2  3  4  5  6  7  8  9] [[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]
-------
[0 1 2 3]
[[0 1]
 [2 3]]
[0 1 2 3]
[[10  1]
 [ 2  3]]


In [ ]:
# different np operations :
import numpy as np

a = np.eye(2) # the unit matrix
b = np.ones([2,2]) # 2X2 ones
c = np.random.random(size=2) # random numbers from 0 to 1
print(np.add(a,b)) # addition
print(np.multiply(a,b)) # element wise
print(np.dot(a,b)) # matrix multiply
print(np.dot(b,c.T)) # matrix times column
print(np.dot(c,c)) # dot product

print('-------')

v = np.array([1, 2, 3, 5])
vand = np.vander(v, 3)  # generates a vanderomnde matrix from v with 3 columns
print(vand)


In [ ]:
# np indexing and slicing :
import numpy as np 

v = np.arange(6)
v1 = v[2] # choosing a specific element
v2= v[1:] # startin from the second
v2[1] = 0
print(v,v2) # changes v too!
u = np.arange(10)
u1 = u[1:].copy()
u1[1] = 0
print(u, u1) # copy fixes it

print('----------')

u2 = u[::-1] # reverse
u3 = u[2:8:2] # taking 2 to 8 in 2 jumps
u4 = u[10:2:-3]  # end to 2 in -3 jumps  (backwards)
print(u4)
u5 = u>5 # true false array
print(u5)
print(u[u5]) # u where is u5 is true only!

print('--------')

# some with matrices :
a = np.array([[1, -1, 10], [2, -2, 20], [3, -3, 30]])
print(a[1,2])  # a specific element in a
print(a[:2]) # the first two rows
print(a[:2, :2]) # removing the last row and column
print(a[:3, 2]) # last element in each row
print(a[a % 2 == 0]) # takes only the evens in a row

print('--------')

b = np.arange(15).reshape(3, 5)  # 0 to 14 reshaped in 3X5
b1 = b[[1,2], [3,4]]  # takes only the (1,3), (2,4) elements in a row
print(b)
print(b1)
b2 = b[b<12]
b3 = b2[b2 % 3 == 1]
print(b3)  # all the element in b that are 1 mod 3 and < 12


In [ ]:
# broadcasting:
import numpy as np

# the rule is that the correspinding dimensions should be the same or one
# has to be equel to 1.

v = np.array([1, 2, 3])  # (1,3)
a = np.array([1,2])  # (1,2)
#print(v+a)  #wont work because 2!=3!=1
aa = np.array([[1],[2]])   # (2,1) could alls be done with reshape(2,1)
print(aa + v)   # copies another row of v and adds elementwise

print('--------')

m = np.arange(9).reshape(3,3)  #(3,3)
print(np.dot(v,m)) # reguler row times matrix
print(v*m) # with broadcastig turns v to (3,3)
# a*m cant be broadcasted 2!=3!=1


print('--------')


# function vectorize :
# turn a reguler function into an element wise vector function.

def absu(x) :
  if x < 0  :
   return -x 
  else :
    return x

vabsu = np.vectorize(absu)   
a = np.array([1, -1, -2, 3, -4])
print(vabsu(a)) # works on a element wise

[[2 3 4]
 [3 4 5]]
--------
[24 30 36]
[[ 0  2  6]
 [ 3  8 15]
 [ 6 14 24]]
--------
[1 1 2 3 4]


In [ ]:
import numpy as np 
# choose :

my_array = np.array([[1,4,5],[2,6,9],[3,7,8]])
choices1 = np.array([1,2,0])  
print(np.choose(choices1,my_array))  # the row you choose from is the number. the place in the row you chose from is the index of the number.
# choose can allso broadcast :
array = np.array([5,6,7])                     # turns array to [[5,6,7],[5,6,7]] and choses according to choices2 to create a 3X2 matrix
choices2 = np.array([[1,0],[1,2],[2,0]])
print(np.choose(choices2,array))

print('--------')

# select :

a = np.arange(12)
choices3 =[a]
conds3 = [a>3]
print(np.select(conds3, choices3))  # returns numbers from a according to condintions. zero otherwise.
choices4 = [a, a**3]
conds4 = [a<4, a>8]  # can also work with several lists and conditions. takes a<4 from a and a>8 from a**3
print(np.select(conds4,choices4))

print('--------')

# where :

print(np.where(a < 5, a, a + 1))  # takes condition,list, and what to do with rest of the list
print(np.where(a < 5, a, 0)) # same as select.  select < where
b = [True,False,False,False,True,False,True,True,False,False,True,False]
print(np.where(b, a, np.sqrt(a)))  # takes from a if true else takes sqrt(a)

print('---------')

# extra stuff : sum

u = np.arange(5)
print(u.sum())  # basic suming up array
print(u.sum(initial=2))  # adds 2 to the sum
m = np.vander(u,3)
print(m)
print(np.sum(m,axis=0), np.sum(m,axis=1))  # sums the rows and columns
print(np.sum(m[3]))  # the sum of a specific row in a given matrix
print(np.sum(m.T[1])) # the sum of a specific column in a given matrix



In [ ]:
# integration :
import numpy as np
import scipy.integrate as integrate 

# standard intagral : 
f1 = lambda x : np.cos(np.exp(x))  # anonymous function of x

res1 = integrate.quad(f1, 0, 1) # the integral from 0 to 1 of f1. returns value and error estimate
print(res1)

print('---------')

# with parameters :

def f2(a,b,x) :
  return a*np.sqrt(x+b)   # function with pars

def res2(a,b,c,d) :
  return integrate.quad(lambda x : f2(a,b,x), c, d) # integrates f2 with chosen pars in chosen bounds

print(res2(2,6,1,5)) # example

print('---------')

# double integral :
 
f3 = lambda x,y : x**2 + y**3 + x*y
res3 = integrate.dblquad(f3, 0, 1, 1, 2)  # integrates f3 over  0<x<1 , 1<y<2  
print(res3)

print('---------')

# samples integration, given samples and not the whole function :

x = np.array([0, 0.25, 0.5, 0.75, 1])
y = np.array([2, 4.11, 5.2, 6.77, 3])

res11 = integrate.simps(y,x)  # two ways of approximating with samples from f
res22 = integrate.trapz(y,x)
print(res11, res22)






In [ ]:
# optimazation :

import numpy as np
from scipy import optimize 
import matplotlib.pyplot as plt

# one variable min :

f1 = lambda x : np.cos(x) - 3*np.sin(x) + x**2
x = np.linspace(0,2,100)   
y = f1(x)
plt.plot(x,y)   
min1 = optimize.minimize_scalar(f1)  # standard scalar function minimum
print(min1)
plt.plot(np.array([min1.x]),np.array(min1.fun),'g*',label='the min')   # mark the min
plt.legend()


print('-----------')


min2 = optimize.fminbound(f1, 1.6, 2)  # minimum with bounds
print(min2)
print('-----------')

# one variable root :

rootf11 = optimize.bisect(f1, 0, 1) # function root with bisection. bounds must be opposite sign
print(rootf11)
print('-----------')

rootf12 = optimize.brentq(f1, 1, 2)  # better method usually
print(rootf12)


In [ ]:
# two variable optimization : 

import numpy as np 
from scipy import optimize
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d

def f1(x,y) :
  return x**4 + y**2 - 10*x*y
x = np.linspace(-15, 15, 100)               # plotting a surface
y = np.linspace(-10, 20, 100)
X, Y = np.meshgrid(x, y)     # the cordiniate matrix of x,y
Z = f1(X, Y)                  # f1 of it. the surface equation
fig = plt.figure()
ax = plt.axes(projection='3d')
ax.plot_surface(X, Y, Z)

def f(u) :
  f = u[0]**4 + u[1]**2 - 10*u[0]*u[1]
  return f

def jf(u) :
  df = np.array([4*u[0]**3 - 10*u[1], 2*u[1] - 10*u[0]])
  return df

# min no constraints no jac :
print(optimize.minimize(f, np.array([5, 15]), method='nelder-mead'))  # takes function and initial guess
print('---------')

# min no constraints yes jac :
print(optimize.minimize(f, np.array([5, 15]), method='BFGS', jac=jf))   # faster with jacobian
print('----------')

# min with conastraints :
ineq_cons = {'type': 'ineq','fun' : lambda x : x[1]-x[0], 'jac' : lambda x : np.array([-1,1])}   # fun>0 and its jac
eq_cons = {'type': 'eq', 'fun' : lambda x : x[0]**2-x[1], 'jac' : lambda x : np.array([2*x[0], -1])}  # fun=0 and its jac
print(optimize.minimize(f,np.array([1,0]),method='SLSQP',jac=jf,constraints=[eq_cons,ineq_cons]))
print('----------')

# global min with bounds :
b = [(-1,1),(2,10)]  
print(optimize.shgo(f,b))
print('----------')
print(optimize.dual_annealing(f,b))
print('----------')


# numerical jacobian :
def numeric_jf(u) :
  h = 10**(-4)   # the small derivitive h
  ndf = np.array([(f(u+np.array([h,0]))-f(u))/h,(f(u+np.array([0,h]))-f(u))/h])  # der approx
  return ndf
print(optimize.minimize(f, np.array([5, 15]), method='BFGS', jac=numeric_jf ))   # can compere yes/no jac and num/reguler jac
print('----------')

# for function max you can do the same procces for -f and take the x value and -fun value



In [ ]:
# roots of vector functions :
import numpy as np
from scipy import optimize

def f(x) :
  return np.array([x[0] + x[1]**2 - 5, x[0]**2 - 6])
 
def jf(x) :
  return np.array([[1,2*x[1]], [2*x[0], 0]])
                   
x0 = np.array([2,5])
print(optimize.root(f,x0))   # only guess
print('------------------')
print(optimize.root(f,x0,jac=jf))  # guess and jac. better!

print('------------------')

# max example :

f = lambda x : np.sqrt(x) + np.cos(x*np.pi)
ff = lambda x : -1*f(x)
max = optimize.fminbound(ff,1,3)
print(max) # the x value
print(f(max)) # the max of f on [1,3]


In [ ]:
# profiler, time it and regression

import numpy as np
from scipy.linalg import lstsq
import matplotlib.pyplot as plt

# an example sorting algorithm :



def sort1(array) :
  a = array.copy()  # copy of the input
  l = array.size     # input size
  new = np.array([])  # empty array. will be the output
  for i in range(l) :   # along input
    min = np.amin(a)     # taking the min
    new = np.append(new,[min])  # adding it to output in the start
    place = np.argwhere(a == min)
    p = place[0,0]
    a = np.delete(a, p)      # deleting the min from a and again, a without the last min
  return(new) 

%prun s = sort1(np.array([1,-1,5,-2,6,4,-11,12,33,45,-12,-5,-4]))
print(s)
                                         # size     time ms
#%timeit  sort1(np.array([1]))            #  1         40
#%timeit  sort1(np.array([1,-1,]))        #  2         83
#%timeit  sort1(np.array([1,-1,5]))       #  3         113
#%timeit  sort1(np.array([1,-1,5,-2]))    #  4         148
#%timeit  sort1(np.array([1,-1,5,-2,6]))  #  5         186

print('------------')

x = np.array([1,2,3,4,5])
y = np.array([40,83,113,148,186])
#plt.plot(x,y,'o')  # looks linear
ones = np.ones([5,1])
m = np.concatenate((x.reshape([5,1]),ones),axis=1)
sol =  lstsq(m,y)  # llstsq to a linear function
a,b = sol[0]  # target is b+a*x
xx = np.linspace(1,5,50)
yy = b + a*xx
plt.plot(x,y,'o', xx,yy,'-')  # plotting them together

%timeit sort1(np.array([1,-2,3,5,-7,34,6,-85,23,-1]))  # 10 long array sort time
print(b+a*10)  # our approx time

# this algo is o(n)

In [ ]:
#  linalg uses :
import numpy as np
import matplotlib.pyplot as plt
from scipy import linalg


# least squares linear regression :

x = np.array([[1.5,2.3,3,3.5,3.9,4.2,5,5.5,6]])             # set of x values
y = np.array([[2, 3.1, 4.4, 6, 10, 16.9, 21, 25.33, 28]])              # set of y values
x1 = np.log(x)                               # the target function is y =a*log(x)+b*x**2
x2 = x**2 
s = np.concatenate((x1.T, x2.T), axis=1)                 
sol = linalg.lstsq(s, y.T)                       # solves it with least squares
a, b = sol[0]              # the coefficients
xx = np.linspace(1.5,6,50)
yy = a*np.log(xx) + b*xx**2
plt.plot(x[0],y[0],'o',label='original samples')         # label once. 'o' so it will apear in dots without lines
plt.plot(x[1:],y[1:],'o')
plt.plot(xx,yy,label='fitted curve')
plt.legend()
plt.xlabel('time',fontsize=15,color='r')              #axes labels
plt.ylabel('population',fontsize=15,color ='r')

print('-------------')

# linear eq system :  m*u=v

# if m is invertible :

m0 = np.array([[1.2,5,4.6],[2.2,3.4,6.68],[3,4.56,6.78]])  # invertible 3X3 matrix
v0 = np.array([1, 1.23, 2.34]) 
m00 = linalg.inv(m0)
u01 = np.dot(m00,v0.T) # u0 = inv(m0)*v0
u02 = linalg.solve(m0,v0.T)  # better
print(u01,u02)
print(np.dot(m0,u02))  # exact solution

print('-----------')

# more general : pinv

m1 = np.array([[1.5, 1.79, 2.45],[1.35, 4.11, 2.5],
               [1.52 ,1, 2.9],[1, 3.55, 2.77]])            # 4X3 matrix !

v1 = np.array([1.45, 2.33, 1.56, 4.4])  # 4X1 sol column
m11 = linalg.pinv(m1)    # a psuedo inverse with least squares. 3x4
u1 = np.dot(m11,v1.T)
print(u1)
print(np.dot(m1,u1.T))  # not exact but not very far

print('------')

# eigen

t = np.array([[2,0,0],[0,1,0],[0,0,2]])
w, v = linalg.eig(t)   
print(w)  # eig  values with repetition
print(v)  # normalized eig vectors

In [ ]:
 # non linear regression : 

import numpy as np
from scipy.optimize import least_squares 
import matplotlib.pyplot as plt


def model(x,t) :
  return x[0]*np.log(x[1]*t+x[2])   # our model function

def target(x,t,y) :
  return model(x,t) - y     # setting it equel to y for our y values

def jac(x,t,y) :
  j = np.empty((t.size,x.size))        # the jacobian row with respect to the parameters x multiplied size of t times
  j[:,0] = x[0]
  j[:,1] = (x[0]*t)/(x[1]*t+x[2])
  j[:,2] = x[0]/(x[1]*t+x[2])
  return j

t = np.array([1, 1.1, 1.45, 2, 3.3, 3.73, 4.1, 4.76, 5])   # t sample values
y = np.array([0.5, 0.7, 0.4, 1.1, 0.9, 1.12, 1.34, 1.5, 1.2])  # y sample values
x0 = np.array([1,2,1.2])    # initial guess for the regression

func = least_squares(target,x0,jac=jac,args=(t,y))  # the regression takes all the above parameters.
print(func.x)  # the x results

t1 = np.linspace(1,6,50)
y1 = model(func.x, t1)
plt.plot(t,y,'o', label='data')
plt.plot(t1,y1,'-', label='fitted model')
plt.legend()
plt.xlabel('t',fontsize=15)
plt.ylabel('y',fontsize=15)

In [ ]:
# stats :
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt

var = stats.cosine()  # a random variable of cosine distribution. df : f(x) = (1+cosx)/2pi, x in [-pi,pi] means= 0 , var = (pi^2)/3-2
x = np.linspace(-np.pi,np.pi,100)
y = (1+np.cos(x))/(2*np.pi)
plt.plot(x,y,'-',label='cosine distribution df',linewidth=2.5)
plt.legend(loc='upper left')
# basic actions :
a1 = var.ppf(0.6)  # p(var<a1) = 0.6
a2 = var.ppf(0.9) # p(var>a2) = 0.1, top 10%
b = var.pdf(0.5*np.pi)   # density function at pi/2
c =  var.cdf(0.85)       # c = p(var<0.85)
#plt.fill_between(x[:64],0*y[:64],y[:64],color='g')  # that's the area we want in c
print(a1,a2,b,c)

samps = var.rvs(size=(5,5))  # 25 random number from this dist at 5X5 matrix
#plt.hist(samps,density=True,bins=5)  # hist of the samples. can normalize and select how many bins will be.


In [ ]:
# kde :
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt

data1 = stats.norm(loc=3,scale=0.5).rvs(25)  # 25 randoms from this dist at row . means=3 sd=0.5
f1 = stats.gaussian_kde(data1)  # an estimate of the right density function for data1
x1 = np.linspace(2,4,30)
plt.hist(data1,density=True,bins=8)  
plt.plot(x1,f1(x1))
plt.title('samples vs estimate df')

# t test :

data2 = stats.poisson(mu=2).rvs(25)  # 25 from poisson distribution with means=3
print(stats.ttest_ind(data1,data2))  # compares them. if p value is >0.1 then means are the same


In [ ]:
# boxplot :
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt

data3 = stats.norm().rvs(20)    # twenty from the standard normal dist 
#data3[0] =  5
print(data3)
plt.boxplot(data3)

# the bottom is the min value. until the bottom of the box is the lowest quarter.
# until the the top of the box is the lowest 75%. the top is the max.
# shows if there are weird values.

In [ ]:
# specail matlpotlib : a pie chart
import matplotlib.pyplot as plt

ingredients = ['suger','flour','milk','chocolate','eggs']  # the slices labels
sizes = [10,20,20,40,10]   # slices sizes
explode = (0,0,0,0.11,0)    # explode a slice if >0
colors = ['gray', 'orange', 'c', 'brown', 'y']   # slices colors

plt.pie(x=sizes,explode=explode,labels=ingredients,colors=colors,shadow=True,radius=2, autopct='%1.0f%%')
plt.rcParams['font.size'] = 17  # to increase label sizes



In [ ]:
# sklearn :
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from mpl_toolkits.mplot3d import Axes3D

data = datasets.load_linnerud()
print(data.data)
print(data.DESCR)
fig = plt.figure()
ax = Axes3D(fig)
ax.scatter(data.data[:,0],data.data[:,1],data.data[:,2])  # 3d scatter plot

# dimension reduction :


x = data.data[:,1:]  # taking only the two last variables.
#plt.scatter(x[:,0], x[:,1])
#plt.xlabel('situps')
#plt.ylabel('jumps')

# not very good.


In [ ]:
# different algorithms  :
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.decomposition import PCA as pca

data = datasets.load_linnerud()
algo1 = pca(n_components=2)  
algo1.fit(data.data)   
data1 = algo1.transform(data.data)
print(data1)
plt.scatter(data1[:,0],data1[:,1])


from sklearn.decomposition import TruncatedSVD as svd

algo2 = svd(n_components=2)
algo2.fit(data.data)
data2 = algo2.transform(data.data)
#print(data2)
#plt.scatter(data2[:,0],data2[:,1])


from sklearn.manifold import TSNE as tsne

data3 = tsne().fit_transform(data.data)
#print(data3)
#plt.scatter(data3[:,0],data3[:,1])



In [ ]:
 # clustering :

import numpy as np 
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN, KMeans, MeanShift

np.random.seed(76)
data = 2*np.random.random(size=(20,2))  # some random numbers from 0 to 2
print(data)

#c = DBSCAN(eps=0.4,min_samples=4,metric='euclidean').fit(data).labels_  # can chose max dist, min points in cluster, metric type and more
c = KMeans(n_clusters=4).fit(data).labels_  # can chose number of clusters here
#c = MeanShift(bandwidth=0.6).fit(data).labels_
print(c) # the labels
plt.scatter(data[:,0],data[:,1],c=c)



In [ ]:
# pandas :
# ctrl + v to paste
import pandas as pd 

# click on the folder icon to the left to upload files
# then right click on the file and copy path.

# basics:

d = pd.read_csv(r'/content/pokemon_data.csv.txt')  # a csv file.
#dxl = pd.read_excel(r'/content/pokemon_data.xlsx')  # an excel file.
#print(d.head(3)) # the first 3 rows
#print(d.tail(3))  # the last 3 rows
#print(d[3:6])  # rows 3 to 5 
#print(d.columns)  # gives columns titles
#print(d['Name']) #  a specific column
#print(d['Type 2'][2:6])  # specific rows in a specific column
#print(d[['Name', 'HP']])  # a few columns
#print(d.iloc[0,1]) # a specfic entry by index [i,j]

# iterating:
#for index, row in d.head(10).iterrows():
#  print(index,row)   prints  col | value  2-table up to  row 9
#  print(index,row['Legendary'])   # only the value for legendary up to row 9

# specific rows :
#d.loc[d['Legendary'] == True] # prints the where legendary col is true
#d.loc[d['Attack'] > 120]  # the row where the attack col is > 120
#d.loc[(d['Type 1'] == 'Fire') & (d['Type 2'] == 'Flying')] # two conds
#d.loc[(d['Legendary'] == True) | (d['Sp. Atk'] > 150)]  # or between 2 conds

# describing data :
#d.describe() # gives stats on the data for each value

# sorting :
#d.sort_values('Attack') # sort by attack
#d.sort_values('Attack', ascending=False) # descending
#d.sort_values('Name') # by name alphabeticly
#d.sort_values(['Type 1','Defense'], ascending = [True, False]) # sort by type 1(asc) and then by defense(des)

# adding and deleting a column :
#first method:
#d['Stats Means'] = (d['Defense'] + d['HP'] + d['Sp. Atk'] + d['Sp. Def'] + d['Speed'] + d['Attack'])/6 # new col to the right
#d = d.drop(columns=['Stats Means'])  # removing a col
#second method :
#d['Total'] = d.iloc[:,4:10].sum(axis=1)  
#titles = list(d.columns.values)
#d = d[titles[:10] + [titles[12]] + titles[10:12]] # putting total right after the stats

# saving data :
#d.to_csv('new pokedata.csv',index=False, sep='\t')  # saving the modified data to collab witout the index col and with nice spaces between cols.
# can download the data on the folder icon to the left. same with excel files : .to_excel

# reseting index :
#newd = d.loc[(d['Type 1'] == 'Water') & (d['Type 2'] == 'Ice')]
#newd = newd.reset_index(drop=True)  # Chose to lose the old index

# more filtering :
#d.loc[(d['Generation'] < 3) & (~d['Name'].str.contains('Mega'))] # gen 1,2 remove the megas
#d.loc[d['Name'].str[0] == 'P']  # names starts with P

# value changes
#d.loc[d['Type 1'] == 'Fire','Type 1'] = 'Flame' # fire to flame
#d.loc[d['Type 1'] == 'Fire','Legendary'] = True  # all fire types are now legendary
#d.loc[d['Attack'] > 150,['#', 'Legendary']] = [1, True] # multiple changes

# group by :
#d.groupby(['Type 1']).mean() # give each stat mean for each type 1
#d.groupby(['Type 1']).mean().sort_values('Sp. Atk',ascending=False) # sorted by sp attack and descending
#d.groupby(['Type 1']).sum() # sums each stat for each type 1
#d['Count'] = 1 # adds a new columns of ones
#d.groupby(['Type 1']).count()['Count'] # counts the ones for each type
#d.groupby(['Type 1','Type 2']).count()['Count'] # groups by type 1 then type 2 and counts

# working with large data :

#d5 = pd.read_csv(r'/content/pokemon_data.csv.txt', chunksize=5)  # divides into chunks of 5
#for dd in d5 :
#  print(dd)


newdata = pd.DataFrame(columns=d.columns) # a new empty dataframe with the same cols
newpoke = pd.DataFrame([[0,'Yuval','Fire','Dragon',200,200,200,200,200,200,0,True]],columns=d.columns) # a new pokemom df
#newdata = newdata.append(newpoke,ignore_index=True) # adding it to the empty one
#d = d.append(newpoke,ignore_index=True).sort_values('#') # adding it to d at the start. defualt = bottom 

